version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-1
    volumes:
      - .:/var/www/html/
      - ./vendor:/var/www/html/vendor
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
    depends_on:
      - mysql
    networks:
      - laravel-net

  # MySQL Database
  mysql:
    image: mysql:8
    container_name: laravel-mysql-1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_payroll_project
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net:
